### ISSUE TITLE
Example for the permutation flow shop problem

### ISSUE THREAD

**Issue by leonlan** [N-Wouda/ALNS#106]
I have some old code lying around where I solve the permutation flow shop problem with large neighborhood search / iterated greedy. This example also covers iterated local search, because the heuristic applies the relocate neighborhood after greedily repairing the solution.

Some todos:
- [x] Update code to ALNS V5
- [x] Include 3 destroy operators with different destruction rates
- [x] Include 2 greedy repair operators
- [x] Use the alpha UCB selection mechanism
- [x] Choose an instance. Instances are very easy to parse (using numpy) because it's a single processing times matrix.

**Comment by N-Wouda** [comment]
Is this also something where we could, for example, show the operator coupling matrix in action? Or do all destroy and repair operators work together?

**Comment by leonlan** [comment]
They all work together in this problem. We could manually enforce coupling?

**Comment by N-Wouda** [comment]
We could, but when the example does not require it there's no point. We could perhaps do something with this in the context of #105 (so not for the permutation flow shop problem).
