### ISSUE TITLE
Run example notebooks on Google Colab or Binder

### ISSUE THREAD

**Issue by leonlan** [N-Wouda/ALNS#122]
> We should also allow running the notebooks on Google Colab or Binder, directly from the documentation. This will make it much easier for people to start using our code.

_Originally posted by @N-Wouda in https://github.com/N-Wouda/ALNS/issues/105#issuecomment-1320879772_

**Comment by N-Wouda** [comment]
Binder's really slow to start up. I get annoyed every time I have to use it. Colab's better, but harder to run because we'd need to have a cell somewhere that installs `alns` (but only when running on Colab).

**Comment by leonlan** [comment]
Google Colab notebooks can be made by replacing `github.com/` with `colab.research.google.com/github/`:

https://colab.research.google.com/github/N-Wouda/ALNS/blob/master/docs/source/examples/cutting_stock_problem.ipynb

Some things we need to address to make this notebook run:
- We need to add a preamble with `pip install alns`
- How to access the instance/data files? Hard-code the urls?

**Comment by leonlan** [comment]
To check if we're in Google Colab: https://stackoverflow.com/a/53586419/13184241 
```python
try:
  import google.colab
  IN_COLAB = True
except:
  IN_COLAB = False
```

Manual upload files (assuming we're in colab)

```python
from google.colab import files

if not os.path.isfile(<file-name>):
    uploaded = files.upload()
```

**Comment by N-Wouda** [comment]
I didn't do this in #120 because there's no good way to make this work (most of the other projects I looked at used Binder for this reason). In the end I figured it'd be easy enough for users to manually copy the notebook from the repo (the link to it is at the top of each example), put it on Colab, and download the necessary data. Or just download the repo and have a go at it locally.

**Comment by leonlan** [comment]
> I didn't do this in #120 because there's no good way to make this work in Colab (most of the other projects I looked at used Binder for this reason). In the end I figured it'd be easy enough for users to manually copy the notebook from the repo (the link to it is at the top of each example), put it on Colab, and download the necessary data. Or just download the repo and have a go at it locally.

I think we only need these two changes to each notebook to make it work: 
- We add the preamble to pip install alns if we're in colab. 
- We make an HTTP-request to the github to get the data if we're in colab, otherwise we just read the local file.

I agree that it should not be very hard to get this run locally. Not sure if it's worth the effort.

**Comment by leonlan** [comment]
I'm closing this issue. It's not worth the extra effort from our side to make these notebooks run on Colab.
