### ISSUE TITLE
Adaptive threshold acceptance criterion

### ISSUE THREAD

**Issue by leonlan** [N-Wouda/ALNS#127]
[Máximo et al. (2021)](https://arxiv.org/abs/2012.11021v1) implements a threshold-based acceptance criterion. They do not give a specific name, but the threshold changes adaptively during the search, which is why I named it "adaptive threshold". 

>This threshold is calculated according to the average quality of the solutions obtained after the local search, which is denoted by $\bar{f}$.

**Comment by leonlan** [comment]
I'll probably work on this next year, just like #114.

**Comment by TeoSkondras** [comment]
@leonlan I would love to work on it right now! can you please provide me with some info regarding where this change should be made?

**Comment by N-Wouda** [comment]
@TeoSkondras this should become a new acceptance criterion. You can have a look at the acceptance criteria already in `alns.accept` (`/alns/accept`) to get started!
