### ISSUE TITLE
Some quetions for using ALNS

### ISSUE THREAD

**Issue by rlacjfjin** [N-Wouda/ALNS#137]
First of all, thanks a lot for your sharing ALNS solver framework. 
I have some questions:
1. In addition to customizing the structure of the solution, destroy and repair operators, Isn't there a need to consider other modules(select, accept and stop conditions)?
2.  For the stop criterion, can it be mixed to use(for example, under the time limit condition, because the solution for the improvement is not found for a long time, it is terminated early)? If so, are there any examples to refer to?
3. Are there any articles on similar trade-offs in terms of choosing weights? (Similar to stop criterion)
4. If I want to improve the solver, in addition to the custom module, is it focus on how to choose the weight(such as learn select weights)? 

Looking forward to your reply, thank you.

Zhe.

**Comment by rlacjfjin** [comment]
Thanks, 
But I still have a question:
there are several select strategies and accept criterions. The first idea is to make a combination with these strategy, but it will
take a lot of time. Is there a priority for these policies( select and accept strategy)?

**Comment by leonlan** [comment]
> Thanks, But I still have a question: there are several select strategies and accept criterions. The first idea is to make a combination with these strategy, but it will take a lot of time. Is there a priority for these policies( select and accept strategy)?

I'm not sure if I understand you correctly here. Do you mean if there is any recommended selection scheme and acceptance criterion combination? If so, then yes: the vehicle routing literature generally uses the `RouletteWheel` selection scheme combined with the `SimulatedAnnealing` acceptance criterion. But if you are trying to solve a different problem, then it may well be that there are other combinations that work better.

**Comment by N-Wouda** [comment]
> If so, then yes: the vehicle routing literature generally uses the `RouletteWheel` selection scheme combined with the `SimulatedAnnealing` acceptance criterion.

[To be fair, particularly the (segmented) roulette wheel is used a  a lot largely due to inertia/lack of interest in experimenting with alternatives. I'm doubt it's actually the best method for operator selection - it's just the first thing that's been suggested in the literature.]

**Comment by rlacjfjin** [comment]
Thanks.
I have no other questions.
