### ISSUE TITLE
what's your alns.weights

### ISSUE THREAD

**Issue by Leetungkwan** [N-Wouda/ALNS#141]
what's your alns.weights, when i run the jupyter, it will come to bug which **ModuleNotFoundError: No module named 'alns.weights'**

**Comment by N-Wouda** [comment]
Which notebook are you running, using what ALNS version? Weight schemes (`alns.weights`) were removed in v5. The relevant weight operators are now in `alns.select`, and named `RouletteWheel` and `SegmentedRouletteWheel`.
