### ISSUE TITLE
About other VRP destroy and repair operators

### ISSUE THREAD

**Issue by rlacjfjin** [N-Wouda/ALNS#145]
Hi,
In your cvrp example, the slack-induced substring removal destroy operator is very powerful, it's very nice result for me.
And in VRPTW and VRPPD case, would you recommend some destroy or repair operators?

Thanks.
Zhe

**Comment by rlacjfjin** [comment]
Sorry, 
I found slack-induced substring removal destroy operator and greedy repair operator is also suitable for vrptw, it's my bug cause some wrong result.
And I still want to know substring removal destroy operator also suitable for VRPPD?
Thanks.

**Comment by leonlan** [comment]
Hi @rlacjfjin. Yes, the slack-induced substring removal operator is also suitable for VRP with pickups and deliveries. See [the original paper](https://pubsonline.informs.org/doi/10.1287/trsc.2019.0914), where they apply the operator to VRPPD with time windows.

**Comment by rlacjfjin** [comment]
Thanks. 👍
