### ISSUE TITLE
Add Example with adjacency matrix input

### ISSUE THREAD

**Issue by niksust** [N-Wouda/ALNS#15]
I saw your example of the Traveling Salesman Problem to understand the solution and implementation of the ALNS. 
I was wandering if there was another example of TSP where the input is a distance matrix for nodes. The example TSP file is https://people.sc.fsu.edu/~jburkardt/datasets/tsp/gr17_d.txt

Thank you.

**Comment by N-Wouda** [comment]
I don't have code for this myself, but a distance matrix is a full specification of the graph/nodes. As such, it should be possible to adapt the notebook to this case also. As for plotting solutions without any node coords, well, that might be a bit more difficult!

**Comment by N-Wouda** [comment]
@niksust I believe https://people.sc.fsu.edu/~jburkardt/datasets/tsp/gr17.tsp offers the same problem in TSP format. This might actually work with relatively minimal modification.

**Comment by N-Wouda** [comment]
This issue has not seen activity for some time. Since it does not track an active bug, or feature request that directly relates to the core code, I have decided to close it for now. 

If you feel this is in error @niksust, please let me know!
