### ISSUE TITLE
How to solve vehicle routing problem with multiple capacities?

### ISSUE THREAD

**Issue by Tiara-cmd** [N-Wouda/ALNS#157]
Hello,
Working on a problem with a heterogeneous fleet. I have already solved it using google's ortools but need to use alns to tune the solution. Is there a way to keep track of the vehicles in alns in order to determine the correct capacity? Any suggestions are greatly appreciated.

**Comment by N-Wouda** [comment]
Hi @Tiara-cmd! :wave:

If all you require in terms of heterogeneous fleet is multiple capacities, perhaps have a look at [PyVRP](https://github.com/PyVRP/PyVRP). That's project is dedicated exclusively to VRPs, and supports this out-of-the-box!

**Comment by Tiara-cmd** [comment]
Thx, I'll check it out! Does PyVRP also use adaptive large neighborhood search and allows parameter tuning?

**Comment by N-Wouda** [comment]
No, it does not. PyVRP uses a genetic algorithm combined with a local search procedure. It does have lots of parameters to tune, but the defaults should be pretty good already.

**Comment by Tiara-cmd** [comment]
Unfortunately for my project, ALNS is a requirement for additional tuning. But thanks for quick responses!

**Comment by N-Wouda** [comment]
You could have a look at the [CVRP example notebook](https://alns.readthedocs.io/en/latest/examples/capacitated_vehicle_routing_problem.html) and adjust that to keep track of which vehicles are assigned to which routes? That might be your best bet if ALNS is a hard requirement.
