### ISSUE TITLE
Python 3.12 release

### ISSUE THREAD

**Issue by N-Wouda** [N-Wouda/ALNS#168]
Update `pyproject.toml` and release a version for Python 3.12 (this might already work out of the box, but it's probably good to be explicit).

**Comment by leonlan** [comment]
Maybe also drop support for 3.8 because its [EOL](https://devguide.python.org/versions/) is in 2024-10.

**Comment by N-Wouda** [comment]
Sounds good to me!

**Comment by N-Wouda** [comment]
Done in #174.
