### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by zwh66s** [N-Wouda/ALNS#172]
I can't run the code,how can I start the code?

**Comment by N-Wouda** [comment]
Hi @zwh66s, did you follow the [instructions](https://alns.readthedocs.io/en/latest/setup/installation.html#running-the-examples-locally) for running the example notebooks on your own device?

**Comment by zwh66s** [comment]
Sorry, I'm a beginner. I think there might be a file like main.py that I can run to execute the code, but I can’t seem to find it. So, I’m not sure how to run the entire code.

**Comment by N-Wouda** [comment]
There is no particular entry point - this is a library, not an executable program. If you want to run the example notebooks you should follow the linked documentation. Additionally, the [quickstart template](https://alns.readthedocs.io/en/latest/setup/template.html) explains succinctly what you need to provide when writing your own program using `alns`.
