### ISSUE TITLE
Weight updating scheme

### ISSUE THREAD

**Issue by N-Wouda** [N-Wouda/ALNS#29]
The updating scheme currently used is overly restrictive: it updates the weights using a convex combination of the current weight, and whatever outcome the operator resulted in. That is how it was done (more or less) in the original ALNS paper, but does not reflect recent use of the ALNS metaheuristic in literature. We should also accommodate those cases.

In particular, we need to allow finer control over the weight updating scheme: 
- [x] Allow resets after a certain number of iterations;
- [x] Allow specification of the initial weights, and those after resets;
- [x] Allow for different updating mechanisms: aside from the convex combination scheme we currently use, a simple addition rule (`new_weight = old_weight + <performance outcome>`) is also commonly used.
- [x] Track statistics on operator weights over iterations.

**Comment by N-Wouda** [comment]
I might call this `AdaptiveStrategy` or similar.

**Comment by ZhiWeiCui** [comment]
@N-Wouda I would like to know any progress on `AdaptiveStrategy`, thank you very much for an amazing package.

**Comment by N-Wouda** [comment]
@ZhiWeiCui hi, thanks for reaching out!

There is no progress on this yet -t I have been quite busy the past year or so. If you want, you can open a PR that I'd be happy to review. Otherwise, I might get to it in a few weeks.

Out of curiosity, can you tell me a little more about your use case?

**Comment by ZhiWeiCui** [comment]
I want to solve Dynamic Pickup and Delivery Problem based on ALNS.

The main ideas are as follows: 
1. update scores after in each iteration.
2. update weights after in each segment(a segment is a number of iterations of the ALNS heuristic; here we define a segment as
100 iterations.) based one (1).
![Snipaste_2021-03-05_09-32-49](https://user-images.githubusercontent.com/22850130/110054327-dd388500-7d95-11eb-96af-c38aa5601817.png)
πi is the score of heuristic i obtained during the last segment and θi is the number of times we have attempted
to use heuristic i during the last segment. 

reference:
[1] Ropke, Stefan, and David Pisinger. “An Adaptive Large Neighborhood Search Heuristic for the Pickup and Delivery Problem with Time Windows.” Transportation Science 40, no. 4 (2006): 455–72.

**Comment by N-Wouda** [comment]
@ZhiWeiCui you might also like https://github.com/N-Wouda/OR-Analysis then!

**Comment by N-Wouda** [comment]
@ZhiWeiCui #41 implements, using your notation, $w_{i, j + 1} = w_{i, j} r + (1 - r) \pi_i$. It still needs tests, further documentation, and I will have to update the examples.

This will be part of ALNS v2.0.0, as these are breaking changes.

**Comment by ZhiWeiCui** [comment]
@N-Wouda Thank you very much for the other repositories you recommended, which are equally excellent. I have learned a lot from your repositories.

**Comment by ZhiWeiCui** [comment]
@N-Wouda Thank you very much for the other repositories you recommended, which are equally excellent. I have learned a lot from your repositories.

I have two questions:

1. My question is a little different from yours. Pick-up and delivery are not necessarily Depot, and my question contains Delivery point that has been picked up. My question includes a time window of pick-up and delivery. Where do I need to start to modify your code? ( I know this problem is huge, but if I can get a little guidance from you, I believe I will get started faster.)
![Snipaste_2021-03-12_09-48-00](https://user-images.githubusercontent.com/22850130/110880271-55b0c000-8319-11eb-8c20-6a0e52e99d26.png)


2. I did not find the model by cplex in this repositories. Did I miss something?

**Comment by N-Wouda** [comment]
@ZhiWeiCui re. your points.

1. Forget the operators for now, and take out the ALNS thing for a bit. You'll get to that later.

    In the `Problem` class you'll want to read in a problem instance (data) from some file location. We did this via `Problem.from_file`, but you'd have to reimplement the class for your data.

    You'll likely want to modify the `Item` class to contain your time windows. The next step is to think about how you want to represent a solution instance. I think you can keep the list of routes, and list of unassigned customers. You'll probably want to modify the `Route` class, however, since you probably don't need the whole `Stack`/`Stacks` business for handling costs. A `Route`, for you, could be just a list of customer IDs. In that case you might not even need the `Route` class, although it could simplify your operator code.

    Then, it is time to get an initial solution. IIRC we gave every customer (pickup/delivery) its own route. You could do the same, if it is feasible to use that many vehicles in your problem.

    You now have a feasible initial solution, a solution lay-out, and the whole file I/O set up. If you want/can, you might also implement a `plot()` method on your solution object. This allows you to visually inspect a solution and further tune your operators down the road. I find that to be very helpful.

    Now you can start thinking about the destroy and repair operators. I'd start with a random destroy and random repair operator pair. These are often simple to implement, and allow you to start running the ALNS heuristic. Then slowly add operators as needed. You might eventually also want to do a little bit of local search around a new best solution (`alns.on_best(<func>)` is your friend here), but that's definitely secondary to getting a good set of destroy/repair operators set-up first.

2. It's in the `ilp` branch, I think. But I haven't worked on that part myself so I cannot comment on its contents.

**Comment by ZhiWeiCui** [comment]
It seems that there is no parameter that can control the number of vehicles in your code, or I did not find it.

**Comment by N-Wouda** [comment]
@ZhiWeiCui correct, that was not a part of the problem we were solving.
