### ISSUE TITLE
Speed-up copying in each iteration?

### ISSUE THREAD

**Issue by NH0** [N-Wouda/ALNS#37]
For every operator (destroy and repair), it seems that the returned state must be a (modified) deep copy of the current state passed as a parameter of the operator.
When profiling my implementation, it turns out that copying the state at every operator call takes a lot of time, and slow the algorithm.

Is it possible to do otherwise to make the algorithm faster ?

**Comment by N-Wouda** [comment]
Hey Thibault, thanks for opening an issue!

If you use copying, that's presumably in your operators, and outside the ALNS package. I use copying in the example notebooks to ensure I do not modify best and current solutions, but this is not enforced usage - if you have a better way for your own code, feel free to use that.

In particular, depending on the problem you're solving and the data structure of your solution state, a shallow copy might suffice (I partially got away with that in https://github.com/N-Wouda/PL-Heuristic and https://github.com/N-Wouda/OR-Analysis, which significantly sped-up the process). It depends a lot on the problem type, and the lay-out of a solution instance. The ALNS package makes very limited assumptions about either, so you're free to implement your own way to prevent overwrites.

As a general rule: copying is only needed in the destroy operators, as the repair operators get a copied object already.

**Comment by N-Wouda** [comment]
Could you share a bit more about the lay-out of your State class? How do you track a solution state?

**Comment by NH0** [comment]
Thanks for the quick response !

My bad for the repair operators, I thought it was also needed.

I'm trying to solve a CVRP (Capacitated Vehicule Routing Problem), and my state class has the following attributes :
`instance`
`number_of_depots`
`size`
`capacity`
`distances`
`collect_alns_statistics`
where `instance` is a networkx graph representing the CVRP solution, `distances` is the adjacency matrix of the problem, and other attributes are strings and integers.
My copy method is for the moment : `copy.deepcopy(self)`. It seems necessary to deepcopy the networkx graph because otherwise it seems like some modifications are made even if it wasn't wanted.
I'll take a look at the heuristics you shared to see how you've done it.

For my operators, destroying consists in removing edges in the `instance` attribute, and repairing consists in adding edges.

Is my problem clear to you ?

**Comment by N-Wouda** [comment]
It seems to me that you store immutable problem data on your solution object, like capacity, distances, and size. Those (I think) never change, so can safely be moved off onto a different object, say a `Problem` class. That way they never need to be copied, and the solution state becomes much smaller to copy as a result. You can look at the two heuristics I've linked for the way I've done this, but might not be satisfied with a singleton if your code has any kind of concurrency.

Similarly, statistics should probably be tracked on a different object as well, outside the solution state - they hurt copying here.

A `nx.Graph` object is pretty large, and copying it every iteration is rather expensive. You might be better off with a different representation, say a list of routes, where each route is a list of customers visited in order. You can have a method to_graph() that transforms this into the `nx.Graph` you currently use - say, for plotting. Internally, I'd use a different data structure that's somewhat smaller in size.

Let me know what you think!

**Comment by NH0** [comment]
Great idea ! It even turns out that I already have a list of routes that I use in a statistics object. I'll see if my operators can work with just lists of routes, and change my code accordingly if possible.

For some statistics, such as the list of routes, I need them in the state, because I use them in my operators. Do you have an idea of how I could do it an other way ?
What I want is to know which nodes I destroyed in the destroy operator, and where they were reinserted in the repair operator.

**Comment by N-Wouda** [comment]
If I understand you correctly, you should be able to track two lists on your solution state: `state.routes`, a list of routes, and `state.unassigned`, a list of destroyed/unassigned customers. `unassigned` is always empty when the state is copied at the start of the destroy operator, since the passed-in solution state is made feasible again by the previous iteration's repair operator. As such, it won't really hurt when copying.

Then, your destroy operators are some variations of:
1. Take a customer from an existing route.
2. Append customer to unassigned.

And the repair operators:
1. Take a customer from unassigned.
2. Insert customer into an existing or new route.

Since a route probably needs some metadata, like the load at each leg of the tour, you might want to turn a Route into a dedicated object, `Route`. That's similar to how I did it in https://github.com/N-Wouda/OR-Analysis.

**Comment by NH0** [comment]
Thanks for the reply !

I believe that what you've proposed will work for my heuristic. :)

But I still need to save `state.routes` and `state.unassigned` at each iteration in order to have the stats I need.
As the destroy operator only takes the state (and the random state) as argument, I don't see an other way than to save `state.routes` and `state.unassigned` inside something like `state.statistics`.

For the moment, it's not an issue anymore, because I don't need to launch the algorithm for more than 100 iterations, for which those improvements would not make a considerable difference.

**Comment by N-Wouda** [comment]
@NH0 you are correct in stating that `routes` and `unassigned` should go directly on the `state` object. I do not think all copying is avoidable when finding new solutions (at least, I haven't figured out how yet!). What you should avoid is needless copying, in particular of data that is constant in each iteration. But these two are clearly not immutable :).

Good luck! Seeing as you no longer face this issue, I'm closing it here. If you have any questions or suggestions in the future, feel free to open another issue!
