### ISSUE TITLE
Import error after pip install

### ISSUE THREAD

**Issue by sk-surya** [N-Wouda/ALNS#40]
Getting the follow error on import after pip install

`from alns import ALNS, State`

results in,
ModuleNotFoundError: No module named 'alns.tools'`

'tools' folder missing inside 'alns' folder.
Manually copying tools folder fixes the issue.
Can this be fixed with pip install?

**Comment by N-Wouda** [comment]
Hi @sk-surya, thanks for opening an issue!

Now this is silly. I forgot to make `alns.tools` into an actual Python module (there's not `__init__.py`), so `setuptools.find_package` ignores it. I've fixed that just yet with a new commit, and a build is underway which will automatically update the package on PyPI. If you try again in a few minutes, `alns==1.3.2` should work out of the box.

Thanks again!

**Comment by N-Wouda** [comment]
Just checked - after updating my dependency to `alns==1.3.2` I can no longer reproduce the issue.

**Comment by sk-surya** [comment]
works now. Thanks!
