### ISSUE TITLE
hi, can we use ALNS method on distance matrix ??

### ISSUE THREAD

**Issue by suleman-81** [N-Wouda/ALNS#42]

**Comment by N-Wouda** [comment]
I'm not sure. What problem are you solving? A distance matrix alone is just data, and not something to optimise.

**Comment by suleman-81** [comment]
Thank you for your response.

In my problem i need to find minimum cost route for 22 shops. I already
calculated the cost matrix for it. Now i need to find out the path bs using
ALNS method.

In your code you call the function for ecludian distance. But i have my
cost matrix , so is it possible to calculate it by using my cost matric
instead of that ecludian distance.

**Comment by N-Wouda** [comment]
I assume you mean the TSP example? Then it's a definite yes. You would have to change the evaluation of the objective (in `State.objective()`) to sum the cost matrix `c` over the edges `(i, j)` between shops `i` and `j` that make up your solution.

Something like ```return sum(self.c[i, j] for i, j in self.edges)```, or the like should do!

**Comment by suleman-81** [comment]
Thank you for the clarification. I will check it out and get back to you.

**Comment by N-Wouda** [comment]
Related issue: #15.

**Comment by suleman-81** [comment]
Thanks, I'll check it out.

**Comment by N-Wouda** [comment]
@suleman-81 I'm closing this issue because I have not heard from you for some time. If you something new to discuss, feel free to let me know by opening a new issue. Have a great day!

**Comment by N-Wouda** [comment]
The TSP example has been updated to do more or less exactly this now, resulting in a slight performance improvement as well.
