### ISSUE TITLE
Display Solution Route

### ISSUE THREAD

**Issue by haroonahmed1** [N-Wouda/ALNS#43]
In the TSP example the solution only shows the minimum distance value, Is it possible to display the route as an array which results in minimum distance ?

**Comment by N-Wouda** [comment]
@haroonahmed1 thanks for opening an issue. It's not exactly clear to me what you mean. I show the route as a figure, based on the route implied by the solution's edges. You could look at how I create that graph on how to obtain the route.

**Comment by haroonahmed1** [comment]
Thank you for reply, based on edges I made a function to display route as an array.

**Comment by N-Wouda** [comment]
Great, thanks for letting me know! If you have any further questions, feel free to open another issue.
