### ISSUE TITLE
Hi, can this ALNS be used for binary variables?

### ISSUE THREAD

**Issue by TNQINGYUN** [N-Wouda/ALNS#45]
Hi, if the problem is to optimize a problem with binary variables x_i, and the objective function F(x), then is the ALNS applicable for  such problems. BTW, how to define the dimensions and variable type? Thanks for your time.

**Comment by N-Wouda** [comment]
@TNQINGYUN hi, thanks for opening an issue.

I have a repository [here]() that uses this package to solve a problem with purely binary decisions, so yes, you can use this package for such problems. In general, you can use this package for (at least) all problems that can be expressed as (integer) linear programs.

It is up to you how to model the decisions. That will depend on the problem you're solving, and on what you need in the operators. I don't know if I can give you any further advice without knowing a little more about your problem.

So: which problem are you solving?

**Comment by TNQINGYUN** [comment]
Thanks for your quick reply. BTW, the link in your reply for the binary package did not work.  Can you replace by a new one?

I want to solve a facility location problem with K locations and use binary variable as the decision variable. The decision variable is given as K binary variables, which can be given as the input to evaluate objective function.  I want to find a fast searching heuristic and try ALNS.

**Comment by N-Wouda** [comment]
My apologies, I meant this link: https://github.com/N-Wouda/PL-Heuristic.

You might want to store the K locations in, say, an array on the `State` object. Something like this, perhaps:

```python
from alns import State
import numpy as np
from .data import costs

class Solution(State):
  locs: np.array

  def objective(self) -> float:
    return costs @ self.locs
```

Where I assume you have, say, a data file that contains the numpy array `costs`, which stores the decision costs.

**Comment by TNQINGYUN** [comment]
Thanks. This is very helpful. I will have a try.

**Comment by N-Wouda** [comment]
@TNQINGYUN very good, let me know if you have any further questions!

**Comment by N-Wouda** [comment]
@TNQINGYUN I'm closing this issue because I have not heard from you for some time. If you something new to discuss, feel free to let me know by opening a new issue. Have a great day!
