### ISSUE TITLE
Explain more about this code please.

### ISSUE THREAD

**Issue by maryam2171** [N-Wouda/ALNS#51]
Hello N-Wouda
This is the first time that I want to solve a model with metaheuristics. I want to use ALNS for my VRP-TW model. Could you explain how should I use these files and which file should be changed and adapted with my model?
Thank you.

**Comment by N-Wouda** [comment]
Hi @maryam2171,

You might want to look at #50 for more discussion about time windows. I do not have any ready-made code for the VRP with time windows, however. You can also have a look at the TSP example [here](https://github.com/N-Wouda/ALNS/blob/master/examples/travelling_salesman_problem.ipynb) for how to use the ALNS package.

**Comment by maryam2171** [comment]
Thank you for responding and suggesting the TSP example. 
So what is the application of this code? I mean in what cases we can use it?
Sorry, I'm a beginner with this website and this is my first experience.

**Comment by N-Wouda** [comment]
@maryam2171 I'm not sure what you're asking 😅. The purpose of the TSP example is to solve an instance of TSP. You can use it to solve that problem, or other TSPs like it. VRP is a generalisation of TSP to multiple vehicles, and then VRPTW generalises that to include time windows. You might also have a look [here](https://github.com/N-Wouda/OR-Analysis) for an ALNS heuristic that solves another VRP variant. I have no code for VRPTW, however.

**Comment by maryam2171** [comment]
@N-Wouda yes ,TSP is ok. So If I want to solve electric VRP-TW with ALNS you suggest to focuse on[https://github.com/N-Wouda/OR-Analysis/tree/master/heuristic](url) ? Thank you

**Comment by N-Wouda** [comment]
@maryam2171 maybe, if you are ready to implement things. Do you have a list of operators you want to include in your ALNS heuristic? Do you know why you want those operators, and not others? Have you written that out in some detail on paper? To ease your life a little, you should probably base some of your operators on existing ALNS heuristics for the (electric) VRPTW from the literature. Have you looked for relevant papers?

If your answer to all that is 'yes', you should be ready to start implementing the heuristic. At that point, the OR-Analysis repository I linked might be helpful. But it begins with a good plan! :-)

**Comment by maryam2171** [comment]
yes, I've read some of them but not exactly. thanks for your help. I hope the  OR-Analysis would be useful.

**Comment by alwyn13** [comment]
@N-Wouda hi, I wanted to ask why I can't run the code. It said TypeError: iterate() takes from 4 to 5 positional arguments but 6 were given. I thought it happened in line result = alns.iterate(init, WEIGHTS, DECAY, CRITERION, ITERATIONS). Thank you!

**Comment by N-Wouda** [comment]
@alwyn13 can you open a new issue for this, instead of using this one? And can you link the repository where you found that line? It's not in ALNS.

**Comment by alwyn13** [comment]
> @alwyn13 can you open a new issue for this, instead of using this one? And can you link the repository where you found that line? It's not in ALNS.

Sorry, it's from [OR-Analysis], but I can't open a new issue in that. Can I ask questions from that?

**Comment by N-Wouda** [comment]
@alwyn13 I do not offer any support on that, no. Are you sure you installed the dependencies from the pipenv lock file? It seems to me that you are using ALNS 2.x, whereas that repo was written for ALNS 1.x. Install, say, `alns==1.4.2`.

**Comment by alwyn13** [comment]
> @alwyn13 I do not offer any support on that repository, no. Are you sure you installed the dependencies from the Pipenv lockfile? It seems to me that you are using ALNS 2.x, whereas that repo was written for ALNS 1.x. You should get it to work if you install, say, `alns==1.4.2`, and try again.

Thanks! It works!

**Comment by N-Wouda** [comment]
@alwyn13 great!

**Comment by N-Wouda** [comment]
@maryam2171 I'm closing this issue because I have not heard from you for some time. If you something new to discuss, feel free to let me know by opening a new issue. Have a great day!
