### ISSUE TITLE
JOSS paper

### ISSUE THREAD

**Issue by N-Wouda** [N-Wouda/ALNS#58]
Eventually I want to get a JOSS (journal of open source software) publication out of this package. See [JOSS](https://joss.theoj.org/), and the [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html). See [here](https://github.com/openjournals/joss-reviews/issues) for a list of currently open reviews, to get a feel for the review process.

**Comment by N-Wouda** [comment]
I am iffy if we are at the point yet where a JOSS publication might be possible, but we are definitely not far off.

@leonlan with your recent contributions, would you be willing to co-author an eventual JOSS publication? It's all fairly simple, like 500-1000 words about the package, and uses in existing/upcoming papers. I can draft a first text, and then you could review?

**Comment by leonlan** [comment]
That is an honorable request! I'm happy to contribute to the paper :)

**Comment by N-Wouda** [comment]
We can use this github action for compiling the draft paper: https://github.com/marketplace/actions/open-journals-pdf-generator.

**Comment by N-Wouda** [comment]
I'm toying around with a stub a bit in the `joss-paper` branch.

**Comment by N-Wouda** [comment]
The paper in the `joss-paper` branch is mostly complete. Once we finish the docs, finish the new selection interface, and add a bandit selection scheme, I think we are ready to submit it for review.

**Comment by N-Wouda** [comment]
The JOSS paper is blocked until we finish #73 (#102), #94, and #97. That's not a lot of work anymore, so I think we can have a paper under review in a week or so.

**Comment by N-Wouda** [comment]
This is happening, I submitted a paper earlier today! 🎉

**Comment by N-Wouda** [comment]
I'm closing this issue as there is nothing left to be done before the review process commences elsewhere.

**Comment by N-Wouda** [comment]
The JOSS paper's been published here: https://doi.org/10.21105/joss.05028. 🎉
