### ISSUE TITLE
Mypyc

### ISSUE THREAD

**Issue by N-Wouda** [N-Wouda/ALNS#83]
We have type annotations (almost) everywhere. Those are OK as well, at least according to mypy.

Can we use this to test whether ALNS compiles with [mypyc](https://github.com/mypyc/mypyc)?

**Comment by leonlan** [comment]
Here is a recent [blog post](https://ichard26.github.io/blog/2022/05/compiling-black-with-mypyc-part-1/) on compiling black using mypyc.

**Comment by N-Wouda** [comment]
Cool to see that (apparently?) the typing on ALNS is already at a point where mypyc can compile it without problems. One thing we might do to further improve its performance is by making the types more strict in the existing codebase.

Of course, in an actual ALNS heuristic, most of the time will be spent in the operators. So for practical performance, ALNS is not often the problem. Nonetheless, we can put in some effort to make this work well, and maybe supply mypyc-compiled wheels on PyPI down the line!

**Comment by N-Wouda** [comment]
I'm closing this issue for now. Clearly, the typing is good enough to support mypy, but I am not that convinced this is where we should take `alns`.
