### ISSUE TITLE
Are TA and RRT the same?

### ISSUE THREAD

**Issue by rlacjfjin** [N-Wouda/ALNS#86]
As the title

**Comment by N-Wouda** [comment]
@rlacjfjin thanks for opening an issue! 

I find it difficult to understand your question. What's the same as what? Can you perhaps rephrase, or explain in more detail?

**Comment by N-Wouda** [comment]
No, TA compares against the current solution; RRT against the global best:

```
>>>diff RecordToRecordTravel.py ThresholdAccept.py

<     def __call__(self, rnd, best, current, candidate):
<         # This follows from the paper by Dueck (1993), p. 87.
<         result = (candidate.objective() - best.objective()) <= self._threshold
---
>     def __call__(self, rnd, best, curr, cand):
>         # This follows from the paper by Dueck and Scheueur (1990), p. 162.
>         res = cand.objective() - curr.objective() <= self._threshold
93,153c47
```

Do note that these APIs are not yet set in stone - they are not yet released. In particular, I suspect we might merge RRT and TA into one class, and have the behaviour depend on a parameter.

**Comment by rlacjfjin** [comment]
I'm following your project, and I see new submissions. 
I've checked what has changed, sorry for disturbing you.
It's ok now, 
thanks

**Comment by N-Wouda** [comment]
No worries, I am glad we could clear this up!
