### ISSUE TITLE
Adding pre-commit to the library

### ISSUE THREAD

**Issue by leonlan** [N-Wouda/ALNS#90]
[pre-commit](https://pre-commit.com/) is a library for managing pre-commit git hooks. Since we already have `black`, `mypy`, `flake8`, etc., it's just a matter of installing and configuring pre-commit to make sure all linters/type checkers are run before committing. We can also add many other useful hooks, e.g. any of the [flake8 extensions](https://github.com/DmytroLitvinov/awesome-flake8-extensions), so that we have more consistent style and minimize the unimportant discussions in code reviews.

I use pre-commit in my local environment, not the least because I sometimes forget to run one of the hooks manually. What do you think of adding this to the library?

**Comment by N-Wouda** [comment]
Sounds like a useful dev-dependency to me. Would you care to setup a PR with the required config file?

**Comment by leonlan** [comment]
Sure thing. I'll submit a PR next week.

**Comment by N-Wouda** [comment]
@leonlan is this still something you want to do?

**Comment by leonlan** [comment]
Yea, I'll submit a PR this weekend.

**Comment by leonlan** [comment]
#112 adds a simple configuration for pre-commit. There's a few things more that I'd like to do:
- Add `isort` or `reorder-python-imports` dependency 
- Remove `black`, `mypy` and `flake8` from poetry
- Integrate with [pre-commit.ci](https://pre-commit.ci/) - this I cannot do because I'm not the owner of the repository
