### ISSUE TITLE
Example notebook for CVRP

### ISSUE THREAD

**Issue by leonlan** [N-Wouda/ALNS#91]
Some time ago I wrote a notebook demonstrating how to use ALNS for CVRP [here](https://colab.research.google.com/drive/17lgI6gC1FzuvDFfRcBqtbWExia_hfnvC#scrollTo=-PkKgp3V-s86&uniqifier=1). I'll rewrite it a bit soon and make a pull request for it when I'm done.

**Comment by N-Wouda** [comment]
I think this is a good idea. We have something for TSP already, but the VRP is a much larger class of problems, and one where ALNS is used a lot in practice. It would be good to have a full-length tutorial for a VRP variant in the repository.
